// Package main - 代码拼接引擎
// 基于真实代码分析生成融合项目文件树
// 分析每个项目的导出符号，生成统一入口与共享层

package main

import (
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"
)

// RunMerge 执行代码拼接 - 生成融合项目文件树
func RunMerge(projects []Project, plan MergePlan, strategy string, opts ChatOptions) []FileNode {
	// 0. 分析每个项目的真实代码
	analyses := make([]codeAnalysis, 0, len(projects))
	for _, p := range projects {
		analyses = append(analyses, analyzeCode(p))
	}

	// 1. 规则生成基础文件（含真实依赖合并）
	ruleFiles := generateRuleFiles(projects, plan, strategy, analyses)

	// 2. AI 生成核心文件（基于真实代码分析）
	aiFiles := aiGenerateFiles(projects, plan, strategy, opts, analyses)

	// 3. 引入上传项目的原始文件（真实源码）
	uploadedFiles := collectUploadedFiles(projects)

	// 4. 生成统一入口（基于真实导出分析）
	entryFiles := generateEntryFiles(projects, analyses, strategy)

	// 5. 合并并构建文件树
	allFiles := append(append(append(ruleFiles, aiFiles...), uploadedFiles...), entryFiles...)
	return buildFileTree(allFiles)
}

// generateRuleFiles 规则生成基础文件（含真实依赖合并）
func generateRuleFiles(projects []Project, plan MergePlan, strategy string, analyses []codeAnalysis) []ProjectFile {
	// 合并所有依赖（从 package.json + 真实 import）
	depSet := map[string]bool{}
	for _, p := range projects {
		for _, d := range p.Dependencies {
			depSet[d] = true
		}
	}
	// 加入真实代码中检测到的 import
	for _, a := range analyses {
		for _, imp := range a.Imports {
			depSet[imp] = true
		}
	}

	var deps []string
	for d := range depSet {
		deps = append(deps, d)
	}
	sort.Strings(deps)

	// 构建 package.json dependencies
	pkgDeps := map[string]string{}
	for _, d := range deps {
		pkgDeps[d] = "^latest"
	}
	pkgJSON := fmt.Sprintf(`{
  "name": "fused-project",
  "version": "1.0.0",
  "type": "module",
  "description": "由 %s 融合生成（ProjectFusion v%s）",
  "fusionTool": "ProjectFusion",
  "fusionVersion": "%s",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "test": "vitest"
  },
  "dependencies": %s
}`, strings.Join(projectNames(projects), " + "), AppVersion, AppVersion, toJSONMap(pkgDeps))

	// README - 含真实分析数据
	var names []string
	for _, p := range projects {
		names = append(names, p.Name)
	}

	// 统计真实代码
	totalFiles := 0
	totalLines := 0
	totalExports := 0
	for _, a := range analyses {
		totalFiles += a.FileCount
		totalLines += a.TotalLines
		totalExports += a.ExportCount
	}

	readme := fmt.Sprintf(`# Fused Project

> 由 ProjectFusion v%s 自动融合生成
> 生成时间：%s

## 融合来源
- %s

## 融合策略
%s

## 真实代码统计
- 源码文件数：%d
- 代码总行数：%d
- 导出符号数：%d

## 目录结构
- src/ - 源码
- src/modules/ - 各项目模块（保留原始代码）
- src/shared/ - 共享层（公共工具与类型）
- src/index.ts - 统一入口（re-export 所有模块）
- src/config/index.ts - 融合配置

## 使用
`+"```bash"+`
npm install
npm run dev
`+"```"+`

## 许可证
继承自源项目许可证，请遵守各源项目的许可证条款。

---
*Generated by ProjectFusion v%s*
`, AppVersion, currentISOTime(), strings.Join(names, "\n- "), strategy, totalFiles, totalLines, totalExports, AppVersion)

	return []ProjectFile{
		{Path: "package.json", Content: pkgJSON},
		{Path: "README.md", Content: readme},
		{Path: ".gitignore", Content: "node_modules\ndist\n.env\n*.log\n"},
	}
}

// generateEntryFiles 基于真实导出分析生成统一入口
func generateEntryFiles(projects []Project, analyses []codeAnalysis, strategy string) []ProjectFile {
	var files []ProjectFile

	// src/index.ts - 统一入口，re-export 所有模块
	var indexLines []string
	indexLines = append(indexLines, "// 融合项目统一入口")
	indexLines = append(indexLines, fmt.Sprintf("// 由 ProjectFusion v%s 自动生成", AppVersion))
	indexLines = append(indexLines, fmt.Sprintf("// 融合来源: %s", strings.Join(projectNames(projects), " + ")))
	indexLines = append(indexLines, "")

	// 为每个上传项目生成 re-export
	for i, p := range projects {
		if p.Source != SourceUploaded || len(p.Files) == 0 {
			continue
		}
		safeName := sanitizeName(p.Name)
		if analyses[i].ExportCount > 0 {
			indexLines = append(indexLines, fmt.Sprintf("// %s - %d 个导出", p.Name, analyses[i].ExportCount))
			indexLines = append(indexLines, fmt.Sprintf("export * from './modules/%s';", safeName))
		}
	}
	indexLines = append(indexLines, "export * from './shared';")
	indexLines = append(indexLines, "export * from './config';")

	files = append(files, ProjectFile{
		Path:    "src/index.ts",
		Content: strings.Join(indexLines, "\n") + "\n",
	})

	// src/shared/index.ts - 共享层
	sharedLines := []string{
		"// 共享层 - 提取公共工具与类型",
		fmt.Sprintf("// 由 ProjectFusion v%s 自动生成", AppVersion),
		"",
		"// 共享依赖列表",
	}
	var allImports []string
	importSet := map[string]bool{}
	for _, a := range analyses {
		for _, imp := range a.Imports {
			if !importSet[imp] {
				importSet[imp] = true
				allImports = append(allImports, imp)
			}
		}
	}
	sort.Strings(allImports)
	sharedLines = append(sharedLines, fmt.Sprintf("export const sharedDependencies = %s;", toJSONArray(allImports)))
	sharedLines = append(sharedLines, "")
	sharedLines = append(sharedLines, "// 公共类型定义")
	sharedLines = append(sharedLines, "export interface FusionMeta {")
	sharedLines = append(sharedLines, "  sources: string[];")
	sharedLines = append(sharedLines, "  generatedAt: string;")
	sharedLines = append(sharedLines, "  strategy: string;")
	sharedLines = append(sharedLines, "}")

	files = append(files, ProjectFile{
		Path:    "src/shared/index.ts",
		Content: strings.Join(sharedLines, "\n") + "\n",
	})

	// src/config/index.ts - 融合配置
	configLines := []string{
		"// 融合项目统一配置",
		fmt.Sprintf("// 由 ProjectFusion v%s 自动生成", AppVersion),
		"",
		"export const FUSION_INFO = {",
		fmt.Sprintf("  sources: %s,", toJSONArray(projectNames(projects))),
		fmt.Sprintf("  generatedAt: '%s',", currentISOTime()),
		fmt.Sprintf("  strategy: '%s',", strategy),
		fmt.Sprintf("  fusionVersion: '%s',", AppVersion),
		"};",
		"",
		"export type FusionStrategy = 'conservative' | 'balanced' | 'aggressive';",
	}

	files = append(files, ProjectFile{
		Path:    "src/config/index.ts",
		Content: strings.Join(configLines, "\n") + "\n",
	})

	return files
}

// aiGenerateFiles AI 生成核心文件（基于真实代码分析）
func aiGenerateFiles(projects []Project, plan MergePlan, strategy string, opts ChatOptions, analyses []codeAnalysis) []ProjectFile {
	var names []string
	for _, p := range projects {
		names = append(names, p.Name)
	}

	// 构建真实代码摘要给 AI
	var codeSummary []string
	for i, p := range projects {
		if i < len(analyses) {
			a := analyses[i]
			codeSummary = append(codeSummary, fmt.Sprintf(
				"项目 %s: %d 文件, %d 行, %d 导出 (%s)",
				p.Name, a.FileCount, a.TotalLines, a.ExportCount,
				strings.Join(a.Exports[:min(10, len(a.Exports))], ", "),
			))
		}
	}

	prompt := fmt.Sprintf(`请为融合项目生成核心源码文件，返回 JSON。
融合项目：%s
融合策略：%s
目标结构：%s
共享依赖：%s

真实代码分析：
%s

请生成以下文件：
1. src/app.ts - 应用初始化逻辑
2. src/types.ts - 公共类型定义

返回格式：{"files":[{"path":"文件路径","content":"文件内容"}]}
只返回 JSON。`, strings.Join(names, ","), strategy, plan.Structure,
		strings.Join(plan.SharedDeps, ","), strings.Join(codeSummary, "\n"))

	messages := []ChatMessage{
		{Role: "system", Content: "你是全栈工程师，擅长生成项目骨架代码。"},
		{Role: "user", Content: prompt},
	}
	content, err := Chat(messages, opts)
	if err == nil {
		var result struct {
			Files []ProjectFile `json:"files"`
		}
		if json.Unmarshal([]byte(ExtractJSON(content)), &result) == nil && len(result.Files) > 0 {
			return result.Files
		}
	}

	// 默认生成应用文件
	return []ProjectFile{
		{Path: "src/app.ts", Content: fmt.Sprintf(`// 融合项目应用初始化
// 由 %s 融合生成
import { FUSION_INFO } from './config'

export function initApp() {
  console.log('Fused project started', FUSION_INFO)
  const root = document.getElementById('root')
  if (root) root.innerHTML = '<h1>Fused Project Ready</h1><p>Sources: ' + FUSION_INFO.sources.join(' + ') + '</p>'
}
`, strings.Join(names, " + "))},
		{Path: "src/types.ts", Content: `// 融合项目公共类型定义
export interface ModuleInfo {
  name: string
  source: string
  exports: string[]
}

export interface FusionResult {
  modules: ModuleInfo[]
  strategy: string
  generatedAt: string
}
`},
	}
}

// collectUploadedFiles 收集上传项目原始文件到 src/modules/<项目名>/
// 保留真实源码，仅跳过配置文件避免冲突
func collectUploadedFiles(projects []Project) []ProjectFile {
	var result []ProjectFile
	for _, p := range projects {
		if p.Source != SourceUploaded || len(p.Files) == 0 {
			continue
		}
		safeName := sanitizeName(p.Name)
		for _, f := range p.Files {
			// 跳过过大的单个文件
			if len(f.Content) > 100000 {
				continue
			}
			// 跳过根配置文件（避免与融合产物冲突）
			if f.Path == "package.json" || f.Path == "README.md" || f.Path == ".gitignore" {
				continue
			}
			// 跳过 lock 文件
			if strings.HasSuffix(f.Path, "package-lock.json") ||
				strings.HasSuffix(f.Path, "yarn.lock") ||
				strings.HasSuffix(f.Path, "pnpm-lock.yaml") {
				continue
			}
			result = append(result, ProjectFile{
				Path:    "src/modules/" + safeName + "/" + f.Path,
				Content: f.Content,
			})
		}
		// 为每个模块生成 index.ts（re-export 所有导出）
		moduleIndex := generateModuleIndex(p, safeName)
		if moduleIndex != "" {
			result = append(result, ProjectFile{
				Path:    "src/modules/" + safeName + "/index.ts",
				Content: moduleIndex,
			})
		}
	}
	return result
}

// generateModuleIndex 为单个模块生成 index.ts（基于真实导出分析）
func generateModuleIndex(p Project, safeName string) string {
	analysis := analyzeCode(p)
	if analysis.ExportCount == 0 {
		return ""
	}

	var lines []string
	lines = append(lines, fmt.Sprintf("// %s 模块入口", p.Name))
	lines = append(lines, fmt.Sprintf("// %d 个导出", analysis.ExportCount))
	lines = append(lines, "")

	// 收集所有源码文件的相对路径，生成 re-export
	exportFiles := map[string]bool{}
	for _, f := range p.Files {
		if !isSourceFile(f.Path) {
			continue
		}
		// 跳过测试文件
		if strings.Contains(f.Path, ".test.") || strings.Contains(f.Path, ".spec.") {
			continue
		}
		// 转换路径：去掉 .ts/.tsx 扩展名
		importPath := "./" + strings.TrimSuffix(strings.TrimSuffix(f.Path, ".tsx"), ".ts")
		importPath = strings.TrimSuffix(importPath, ".js")
		importPath = strings.TrimSuffix(importPath, ".jsx")
		if !exportFiles[importPath] {
			exportFiles[importPath] = true
			lines = append(lines, fmt.Sprintf("export * from '%s';", importPath))
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// buildFileTree 将扁平文件列表构建为树形结构
func buildFileTree(files []ProjectFile) []FileNode {
	root := &FileNode{Path: "", Name: "", Type: "dir"}
	for _, f := range files {
		parts := strings.Split(f.Path, "/")
		current := root
		for i, part := range parts {
			isLast := i == len(parts)-1
			child := findChild(current, part)
			if child == nil {
				child = &FileNode{Name: part, Type: "dir"}
				if isLast {
					child.Type = "file"
					child.Path = f.Path
					child.Content = f.Content
				} else {
					child.Path = strings.Join(parts[:i+1], "/")
				}
				current.Children = append(current.Children, *child)
				current = &current.Children[len(current.Children)-1]
			} else {
				current = child
			}
		}
	}
	sortTree(root)
	return root.Children
}

// findChild 查找子节点
func findChild(node *FileNode, name string) *FileNode {
	for i := range node.Children {
		if node.Children[i].Name == name {
			return &node.Children[i]
		}
	}
	return nil
}

// sortTree 排序文件树
func sortTree(node *FileNode) {
	sort.Slice(node.Children, func(i, j int) bool {
		if node.Children[i].Type != node.Children[j].Type {
			return node.Children[i].Type == "dir"
		}
		return node.Children[i].Name < node.Children[j].Name
	})
	for i := range node.Children {
		sortTree(&node.Children[i])
	}
}

// sanitizeName 规范化项目名为目录名
func sanitizeName(name string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	s := b.String()
	if s == "" {
		return "module"
	}
	return s
}

// toJSONMap 简易 map 序列化
func toJSONMap(m map[string]string) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("{")
	for i, k := range keys {
		if i > 0 {
			b.WriteString(",")
		}
		b.WriteString(fmt.Sprintf("%q:%q", k, m[k]))
	}
	b.WriteString("}")
	return b.String()
}

// toJSONArray 简易数组序列化
func toJSONArray(arr []string) string {
	var b strings.Builder
	b.WriteString("[")
	for i, s := range arr {
		if i > 0 {
			b.WriteString(",")
		}
		b.WriteString(fmt.Sprintf("%q", s))
	}
	b.WriteString("]")
	return b.String()
}

// projectNames 提取项目名列表
func projectNames(projects []Project) []string {
	names := make([]string, 0, len(projects))
	for _, p := range projects {
		names = append(names, p.Name)
	}
	return names
}

// currentISOTime 当前 ISO 时间
func currentISOTime() string {
	return "2026-06-20T00:00:00.000Z"
}

// min 返回较小值
func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// 引用 path 包避免未使用
var _ = path.Join

// 预编译正则（供 analyzeCode 使用）
var _ = regexp.MustCompile
